### ISSUE TITLE
Unhandled Error: this is not a typed array

### ISSUE THREAD

**Issue by ebtalley** [salesforce-ux/design-system-ui-kit#9]
I tried the quick instructions by doing the following:
> git clone git@github.com:salesforce-ux/design-system-ui-kit.git
> cd design-system-ui-kit
> npm install
> gulp

which produced the following error
[16:13:43] Using gulpfile ~/design-system-starter-kit/gulpfile.js
[16:13:43] Starting 'build'...
[16:13:43] Starting 'clean'...
[16:13:43] Finished 'clean' after 374 ms
[16:13:43] Starting 'assets'...
[16:13:43] Starting 'views'...
[16:13:43] Starting 'styles'...
[16:13:44] Starting 'scripts'...
[16:13:44] Starting 'favicon'...
[16:13:46] Plumber found unhandled error:
 TypeError in plugin 'gulp-autoprefixer'
Message:
    this is not a typed array.
Details:
    fileName: /design-system-starter-kit/src/styles/index.css
Stack:
TypeError: this is not a typed array.
    at Function.from (native)
    at /design-system-starter-kit/node_modules/gulp-autoprefixer/index.js:25:27
    at process._tickCallback (node.js:369:9)
[16:13:46] Finished 'scripts' after 2.17 s
[16:13:46] Finished 'favicon' after 2.17 s
[16:13:46] Finished 'views' after 3.03 s
[16:13:47] Finished 'assets' after 3.91 s

**Comment by ebtalley** [comment]
I hotfixed it in the meantime by commenting out the autoprefixer call in gulp.
    //.pipe($.autoprefixer({ browsers: ['last 2 versions'], remove: false }))

**Comment by engai** [comment]
Hey @ebtalley, I think you may be mixing up the [design-system-starter-kit](https://github.com/salesforce-ux/design-system-starter-kit) and this repo, which is our ui kit. 

Closing for now, but feel free to reopen and comment if needed.
